### ISSUE TITLE
Azure voice recognition only recognizes english (en-US)

### ISSUE THREAD

**Issue by ScartCable** [TimShaw1/Wendigos-Mod#15]
Azure voice recognition defaults to en-US when `SpeechConfig.SpeechRecognitionLanguage` is not set [(source)](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-speech-to-text?tabs=windows%2Cterminal&pivots=programming-language-csharp). It would be great if you could add a config option to change language.

**Comment by joecabezas** [comment]
+1

**Comment by joecabezas** [comment]
added PR https://github.com/TimShaw1/Wendigos-Mod/pull/18

**Comment by TimShaw1** [comment]
Solved in v1.0.8
