### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by minecraftboy301** [TimShaw1/Wendigos-Mod#2]
The bepinex console is being spammed and makes the game stutter and lag. Starts to happen when any player joins. Happens when your both a host and joiner

https://github.com/TimShaw1/Wendigos-Mod/assets/96290665/52c71b84-1025-4a2c-bf5d-6689176986c2

**Comment by TimShaw1** [comment]
Currently this debug info is needed. Some lag will happen during clip syncing regardless, just wait it out before starting the game
