### ISSUE TITLE
Cannot talk with the masked enemies 

### ISSUE THREAD

**Issue by TESTYEE-09** [TimShaw1/Wendigos-Mod#21]
I have set up everything but I can only hear the prerecord parses even with real time responses enabled.
[LogOutput.log](https://github.com/user-attachments/files/17951535/LogOutput.log)

**Comment by TimShaw1** [comment]
I see in your log:
Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://useast.stt.speech.microsoft.com/speech/universal/v2
[Info   :   Console] CANCELED: Did you set the speech resource key and region values?

Did you set your API key and region correctly?

**Comment by TESTYEE-09** [comment]
Yeah it was a problem with Azure, thanks.
