### ISSUE TITLE
Cant get eleven AI to work

### ISSUE THREAD

**Issue by MatrixMouse** [TimShaw1/Wendigos-Mod#3]
as title says
![image_2024-06-28_155017572](https://github.com/TimShaw1/Wendigos-Mod/assets/174152923/3c72bd59-aea4-4748-9048-ed9dca4df77f)

**Comment by TimShaw1** [comment]
Please post your BepInEx log file here after you interact with a masked so I can see whats up. (Don't worry, it doesn't show your API key)
