### ISSUE TITLE
Will there be more supported languages in the future?

### ISSUE THREAD

**Issue by SteelyxYT** [TimShaw1/Wendigos-Mod#5]
I was wondering if there will be more supported languages in the future since me and my friends talk norwegian together and would make it quite obvious and easy to evade the clones

**Comment by TimShaw1** [comment]
I'm always looking for better local voice cloning models to use! As for now, other improvements have higher priority. Hopefully Elevenlabs adds Norwegian soon if I can't find a model that supports it!
