### ISSUE TITLE
Mod compatibility Issus with FixPluginTypesSerialization by Evaisa

### ISSUE THREAD

**Issue by Turtletnt5** [TimShaw1/Wendigos-Mod#8]
There is a compatibility issue with the FixPluginTypesSerialization by evaisa. The new update seems to have caused the incompatibility as it was previously fine. If you attempt to host a game with the mod installed it causes an infinite loop which eventually crashes the game. The first screenshot below is the error received during initial loading. The second screenshot is of the infinite loop error message.

link to mod page: https://thunderstore.io/c/lethal-company/p/Evaisa/FixPluginTypesSerialization/

![Screenshot 2024-07-16 164647](https://github.com/user-attachments/assets/0aa141f5-a485-4b62-a868-f8c1ac23cb00)

![Screenshot 2024-07-16 162430](https://github.com/user-attachments/assets/4279d428-fd4b-41d1-a727-d80f84137b3d)

The FixPluginTypesSerialization is a requirement for a number of popular mods like LateGame upgrades, CSync
By Sigurd and LethalLevelLoader By IAmBatby.

**Comment by TimShaw1** [comment]
Fixed in 1.0.4
